
// This file has been generated by the GUI designer. Do not modify.
namespace Taquilla
{
	public partial class CorteZ
	{
		private global::Gtk.Label lblTotal;

		private global::Gtk.Table table1;

		private global::Gtk.Label label11;

		private global::Gtk.Label label12;

		private global::Gtk.Label label13;

		private global::Gtk.Label label14;

		private global::Gtk.Label label15;

		private global::Gtk.Label label3;

		private global::Gtk.Label label4;

		private global::Gtk.Label label5;

		private global::Gtk.Label label6;

		private global::Gtk.Label label8;

		private global::Gtk.Label label9;

		private global::Gtk.Entry txtCheque;

		private global::Gtk.Entry txtCredito;

		private global::Gtk.Entry txtEfectivo;

		private global::Gtk.Entry txtMontoRemesar;

		private global::Gtk.Entry txtNoCompras;

		private global::Gtk.Entry txtNota1;

		private global::Gtk.Entry txtNota2;

		private global::Gtk.Entry txtNota3;

		private global::Gtk.Entry txtNota4;

		private global::Gtk.Entry txtNota5;

		private global::Gtk.Entry txtTotalCompras;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Taquilla.CorteZ
			this.Name = "Taquilla.CorteZ";
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Modal = true;
			// Internal child Taquilla.CorteZ.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.lblTotal = new global::Gtk.Label ();
			this.lblTotal.Name = "lblTotal";
			this.lblTotal.LabelProp = "label2";
			w1.Add (this.lblTotal);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(w1[this.lblTotal]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(11)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 1f;
			this.label11.LabelProp = "Nota línea 1";
			this.table1.Add (this.label11);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.label11]));
			w3.TopAttach = ((uint)(6));
			w3.BottomAttach = ((uint)(7));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 1f;
			this.label12.LabelProp = "Nota línea 2";
			this.table1.Add (this.label12);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.label12]));
			w4.TopAttach = ((uint)(7));
			w4.BottomAttach = ((uint)(8));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.Xalign = 1f;
			this.label13.LabelProp = "Nota línea 3";
			this.table1.Add (this.label13);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.label13]));
			w5.TopAttach = ((uint)(8));
			w5.BottomAttach = ((uint)(9));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.Xalign = 1f;
			this.label14.LabelProp = "Nota línea 4";
			this.table1.Add (this.label14);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.label14]));
			w6.TopAttach = ((uint)(9));
			w6.BottomAttach = ((uint)(10));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.Xalign = 1f;
			this.label15.LabelProp = "Nota línea 5";
			this.table1.Add (this.label15);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.label15]));
			w7.TopAttach = ((uint)(10));
			w7.BottomAttach = ((uint)(11));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 1f;
			this.label3.LabelProp = "Efectivo";
			this.table1.Add (this.label3);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.label3]));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 1f;
			this.label4.LabelProp = "P.O.S";
			this.table1.Add (this.label4);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.label4]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 1f;
			this.label5.LabelProp = "Cheque";
			this.table1.Add (this.label5);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.label5]));
			w10.TopAttach = ((uint)(2));
			w10.BottomAttach = ((uint)(3));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 1f;
			this.label6.LabelProp = "Monto a remesar";
			this.table1.Add (this.label6);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.label6]));
			w11.TopAttach = ((uint)(3));
			w11.BottomAttach = ((uint)(4));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xalign = 1f;
			this.label8.LabelProp = "No. compras";
			this.table1.Add (this.label8);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.label8]));
			w12.TopAttach = ((uint)(4));
			w12.BottomAttach = ((uint)(5));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.Xalign = 1f;
			this.label9.LabelProp = "Total compras";
			this.table1.Add (this.label9);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.label9]));
			w13.TopAttach = ((uint)(5));
			w13.BottomAttach = ((uint)(6));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtCheque = new global::Gtk.Entry ();
			this.txtCheque.CanFocus = true;
			this.txtCheque.Name = "txtCheque";
			this.txtCheque.Text = "0.00";
			this.txtCheque.IsEditable = true;
			this.txtCheque.InvisibleChar = '•';
			this.table1.Add (this.txtCheque);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.txtCheque]));
			w14.TopAttach = ((uint)(2));
			w14.BottomAttach = ((uint)(3));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtCredito = new global::Gtk.Entry ();
			this.txtCredito.CanFocus = true;
			this.txtCredito.Name = "txtCredito";
			this.txtCredito.Text = "0.00";
			this.txtCredito.IsEditable = true;
			this.txtCredito.InvisibleChar = '•';
			this.table1.Add (this.txtCredito);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.txtCredito]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtEfectivo = new global::Gtk.Entry ();
			this.txtEfectivo.CanFocus = true;
			this.txtEfectivo.Name = "txtEfectivo";
			this.txtEfectivo.Text = "0.00";
			this.txtEfectivo.IsEditable = true;
			this.txtEfectivo.InvisibleChar = '•';
			this.table1.Add (this.txtEfectivo);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.txtEfectivo]));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtMontoRemesar = new global::Gtk.Entry ();
			this.txtMontoRemesar.CanFocus = true;
			this.txtMontoRemesar.Name = "txtMontoRemesar";
			this.txtMontoRemesar.Text = "0.00";
			this.txtMontoRemesar.IsEditable = false;
			this.txtMontoRemesar.InvisibleChar = '•';
			this.table1.Add (this.txtMontoRemesar);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1[this.txtMontoRemesar]));
			w17.TopAttach = ((uint)(3));
			w17.BottomAttach = ((uint)(4));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(2));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtNoCompras = new global::Gtk.Entry ();
			this.txtNoCompras.CanFocus = true;
			this.txtNoCompras.Name = "txtNoCompras";
			this.txtNoCompras.Text = "0";
			this.txtNoCompras.IsEditable = true;
			this.txtNoCompras.InvisibleChar = '•';
			this.table1.Add (this.txtNoCompras);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1[this.txtNoCompras]));
			w18.TopAttach = ((uint)(4));
			w18.BottomAttach = ((uint)(5));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtNota1 = new global::Gtk.Entry ();
			this.txtNota1.CanFocus = true;
			this.txtNota1.Name = "txtNota1";
			this.txtNota1.IsEditable = true;
			this.txtNota1.MaxLength = 30;
			this.txtNota1.InvisibleChar = '●';
			this.table1.Add (this.txtNota1);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1[this.txtNota1]));
			w19.TopAttach = ((uint)(6));
			w19.BottomAttach = ((uint)(7));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtNota2 = new global::Gtk.Entry ();
			this.txtNota2.CanFocus = true;
			this.txtNota2.Name = "txtNota2";
			this.txtNota2.IsEditable = true;
			this.txtNota2.MaxLength = 30;
			this.txtNota2.InvisibleChar = '●';
			this.table1.Add (this.txtNota2);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1[this.txtNota2]));
			w20.TopAttach = ((uint)(7));
			w20.BottomAttach = ((uint)(8));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtNota3 = new global::Gtk.Entry ();
			this.txtNota3.CanFocus = true;
			this.txtNota3.Name = "txtNota3";
			this.txtNota3.IsEditable = true;
			this.txtNota3.MaxLength = 30;
			this.txtNota3.InvisibleChar = '●';
			this.table1.Add (this.txtNota3);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1[this.txtNota3]));
			w21.TopAttach = ((uint)(8));
			w21.BottomAttach = ((uint)(9));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtNota4 = new global::Gtk.Entry ();
			this.txtNota4.CanFocus = true;
			this.txtNota4.Name = "txtNota4";
			this.txtNota4.IsEditable = true;
			this.txtNota4.MaxLength = 30;
			this.txtNota4.InvisibleChar = '●';
			this.table1.Add (this.txtNota4);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1[this.txtNota4]));
			w22.TopAttach = ((uint)(9));
			w22.BottomAttach = ((uint)(10));
			w22.LeftAttach = ((uint)(1));
			w22.RightAttach = ((uint)(2));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtNota5 = new global::Gtk.Entry ();
			this.txtNota5.CanFocus = true;
			this.txtNota5.Name = "txtNota5";
			this.txtNota5.IsEditable = true;
			this.txtNota5.MaxLength = 30;
			this.txtNota5.InvisibleChar = '●';
			this.table1.Add (this.txtNota5);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1[this.txtNota5]));
			w23.TopAttach = ((uint)(10));
			w23.BottomAttach = ((uint)(11));
			w23.LeftAttach = ((uint)(1));
			w23.RightAttach = ((uint)(2));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtTotalCompras = new global::Gtk.Entry ();
			this.txtTotalCompras.CanFocus = true;
			this.txtTotalCompras.Name = "txtTotalCompras";
			this.txtTotalCompras.Text = "0.00";
			this.txtTotalCompras.IsEditable = true;
			this.txtTotalCompras.InvisibleChar = '•';
			this.table1.Add (this.txtTotalCompras);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1[this.txtTotalCompras]));
			w24.TopAttach = ((uint)(5));
			w24.BottomAttach = ((uint)(6));
			w24.LeftAttach = ((uint)(1));
			w24.RightAttach = ((uint)(2));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add (this.table1);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(w1[this.table1]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			// Internal child Taquilla.CorteZ.ActionArea
			global::Gtk.HButtonBox w26 = this.ActionArea;
			w26.Name = "dialog1_ActionArea";
			w26.Spacing = 10;
			w26.BorderWidth = ((uint)(5));
			w26.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w27 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w26[this.buttonCancel]));
			w27.Expand = false;
			w27.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			// Container child buttonOk.Gtk.Container+ContainerChild
			global::Gtk.Alignment w28 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w29 = new global::Gtk.HBox ();
			w29.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w30 = new global::Gtk.Image ();
			w30.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-print", global::Gtk.IconSize.Menu);
			w29.Add (w30);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w32 = new global::Gtk.Label ();
			w32.LabelProp = "_Imprimir";
			w32.UseUnderline = true;
			w29.Add (w32);
			w28.Add (w29);
			this.buttonOk.Add (w28);
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w36 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w26[this.buttonOk]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 467;
			this.Show ();
			this.txtEfectivo.TextInserted += new global::Gtk.TextInsertedHandler (this.OnTxtEfectivoTextInserted);
			this.txtCheque.TextInserted += new global::Gtk.TextInsertedHandler (this.OnTxtChequeTextInserted);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
