
// This file has been generated by the GUI designer. Do not modify.
namespace Taquilla
{
	public partial class pases
	{
		private global::Gtk.HBox hbox1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label label1;
		private global::Gtk.Entry txtCantidadDeBoletos;
		private global::Gtk.Label label2;
		private global::Gtk.Table table1;
		private global::Gtk.CheckButton chkDomingo;
		private global::Gtk.CheckButton chkJueves;
		private global::Gtk.CheckButton chkLunes;
		private global::Gtk.CheckButton chkMartes;
		private global::Gtk.CheckButton chkMiercoles;
		private global::Gtk.CheckButton chkSabado;
		private global::Gtk.CheckButton chkViernes;
		private global::Gtk.Entry txtPrecioBoletos;
		private global::Gtk.Label label3;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Calendar calCaducidad;
		private global::Gtk.Entry txtRazonBoletos;
		private global::Gtk.Label label4;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Taquilla.pases
			this.Name = "Taquilla.pases";
			this.Title = "Generador de pases";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Taquilla.pases.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = "Cantidad de boletos";
			this.vbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.txtCantidadDeBoletos = new global::Gtk.Entry ();
			this.txtCantidadDeBoletos.CanFocus = true;
			this.txtCantidadDeBoletos.Name = "txtCantidadDeBoletos";
			this.txtCantidadDeBoletos.Text = "0";
			this.txtCantidadDeBoletos.IsEditable = true;
			this.txtCantidadDeBoletos.InvisibleChar = '●';
			this.vbox2.Add (this.txtCantidadDeBoletos);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.txtCantidadDeBoletos]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = "Días habilitados";
			this.vbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label2]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.chkDomingo = new global::Gtk.CheckButton ();
			this.chkDomingo.CanFocus = true;
			this.chkDomingo.Name = "chkDomingo";
			this.chkDomingo.Label = "Domingo";
			this.chkDomingo.DrawIndicator = true;
			this.chkDomingo.UseUnderline = true;
			this.table1.Add (this.chkDomingo);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.chkDomingo]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.chkJueves = new global::Gtk.CheckButton ();
			this.chkJueves.CanFocus = true;
			this.chkJueves.Name = "chkJueves";
			this.chkJueves.Label = "Jueves";
			this.chkJueves.Active = true;
			this.chkJueves.DrawIndicator = true;
			this.chkJueves.UseUnderline = true;
			this.table1.Add (this.chkJueves);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.chkJueves]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.chkLunes = new global::Gtk.CheckButton ();
			this.chkLunes.CanFocus = true;
			this.chkLunes.Name = "chkLunes";
			this.chkLunes.Label = "Lunes";
			this.chkLunes.Active = true;
			this.chkLunes.DrawIndicator = true;
			this.chkLunes.UseUnderline = true;
			this.table1.Add (this.chkLunes);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.chkLunes]));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.chkMartes = new global::Gtk.CheckButton ();
			this.chkMartes.CanFocus = true;
			this.chkMartes.Name = "chkMartes";
			this.chkMartes.Label = "Martes";
			this.chkMartes.Active = true;
			this.chkMartes.DrawIndicator = true;
			this.chkMartes.UseUnderline = true;
			this.table1.Add (this.chkMartes);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.chkMartes]));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.chkMiercoles = new global::Gtk.CheckButton ();
			this.chkMiercoles.CanFocus = true;
			this.chkMiercoles.Name = "chkMiercoles";
			this.chkMiercoles.Label = "Miércoles";
			this.chkMiercoles.Active = true;
			this.chkMiercoles.DrawIndicator = true;
			this.chkMiercoles.UseUnderline = true;
			this.table1.Add (this.chkMiercoles);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.chkMiercoles]));
			w9.LeftAttach = ((uint)(2));
			w9.RightAttach = ((uint)(3));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.chkSabado = new global::Gtk.CheckButton ();
			this.chkSabado.CanFocus = true;
			this.chkSabado.Name = "chkSabado";
			this.chkSabado.Label = "Sábado";
			this.chkSabado.DrawIndicator = true;
			this.chkSabado.UseUnderline = true;
			this.table1.Add (this.chkSabado);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.chkSabado]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.LeftAttach = ((uint)(2));
			w10.RightAttach = ((uint)(3));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.chkViernes = new global::Gtk.CheckButton ();
			this.chkViernes.CanFocus = true;
			this.chkViernes.Name = "chkViernes";
			this.chkViernes.Label = "Viernes";
			this.chkViernes.DrawIndicator = true;
			this.chkViernes.UseUnderline = true;
			this.table1.Add (this.chkViernes);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.chkViernes]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.table1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table1]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.txtPrecioBoletos = new global::Gtk.Entry ();
			this.txtPrecioBoletos.CanFocus = true;
			this.txtPrecioBoletos.Name = "txtPrecioBoletos";
			this.txtPrecioBoletos.Text = "0.00";
			this.txtPrecioBoletos.IsEditable = true;
			this.txtPrecioBoletos.InvisibleChar = '●';
			this.vbox2.Add (this.txtPrecioBoletos);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.txtPrecioBoletos]));
			w13.PackType = ((global::Gtk.PackType)(1));
			w13.Position = 4;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = "Precio boletos";
			this.vbox2.Add (this.label3);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label3]));
			w14.PackType = ((global::Gtk.PackType)(1));
			w14.Position = 5;
			w14.Expand = false;
			w14.Fill = false;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.calCaducidad = new global::Gtk.Calendar ();
			this.calCaducidad.HeightRequest = 184;
			this.calCaducidad.CanFocus = true;
			this.calCaducidad.Name = "calCaducidad";
			this.calCaducidad.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.vbox4.Add (this.calCaducidad);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.calCaducidad]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.txtRazonBoletos = new global::Gtk.Entry ();
			this.txtRazonBoletos.CanFocus = true;
			this.txtRazonBoletos.Name = "txtRazonBoletos";
			this.txtRazonBoletos.IsEditable = true;
			this.txtRazonBoletos.InvisibleChar = '●';
			this.vbox4.Add (this.txtRazonBoletos);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.txtRazonBoletos]));
			w17.PackType = ((global::Gtk.PackType)(1));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = "Razón boletos";
			this.vbox4.Add (this.label4);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label4]));
			w18.PackType = ((global::Gtk.PackType)(1));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			this.hbox1.Add (this.vbox4);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox4]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			w1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox1]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Internal child Taquilla.pases.ActionArea
			global::Gtk.HButtonBox w21 = this.ActionArea;
			w21.Name = "dialog1_ActionArea";
			w21.Spacing = 10;
			w21.BorderWidth = ((uint)(5));
			w21.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			// Container child buttonCancel.Gtk.Container+ContainerChild
			global::Gtk.Alignment w22 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w23 = new global::Gtk.HBox ();
			w23.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w24 = new global::Gtk.Image ();
			w24.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Menu);
			w23.Add (w24);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w26 = new global::Gtk.Label ();
			w26.LabelProp = "_Salir";
			w26.UseUnderline = true;
			w23.Add (w26);
			w22.Add (w23);
			this.buttonCancel.Add (w22);
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w30 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w21 [this.buttonCancel]));
			w30.Expand = false;
			w30.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			// Container child buttonOk.Gtk.Container+ContainerChild
			global::Gtk.Alignment w31 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w32 = new global::Gtk.HBox ();
			w32.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w33 = new global::Gtk.Image ();
			w33.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-print", global::Gtk.IconSize.Menu);
			w32.Add (w33);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w35 = new global::Gtk.Label ();
			w35.LabelProp = "_Imprimir";
			w35.UseUnderline = true;
			w32.Add (w35);
			w31.Add (w32);
			this.buttonOk.Add (w31);
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w39 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w21 [this.buttonOk]));
			w39.Position = 1;
			w39.Expand = false;
			w39.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 548;
			this.DefaultHeight = 333;
			this.Show ();
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
