
// This file has been generated by the GUI designer. Do not modify.
namespace Taquilla
{
	public partial class VisorEventos
	{
		private global::Gtk.Label label1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button cmdEventosVendidosHoy;
		private global::Gtk.Button cmdEventosHoy;
		private global::Gtk.Entry txtIDEvento;
		private global::Gtk.Button cmdBuscarEventos;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeEventos;
		private global::Gtk.Button buttonOk;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Taquilla.VisorEventos
			this.Name = "Taquilla.VisorEventos";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Taquilla.VisorEventos.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = "Búsqueda: se puede búscar por nombre de la persona o nombre del evento. Probar con un nombre o apellido a la vez.\nEdición: para editar un evento, hacer clic sobre el elemento en la lista y presionar la tecla \"<b>e</b>\" (de <b>e</b>ditar).";
			this.label1.UseMarkup = true;
			w1.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(w1 [this.label1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.cmdEventosVendidosHoy = new global::Gtk.Button ();
			this.cmdEventosVendidosHoy.CanFocus = true;
			this.cmdEventosVendidosHoy.Name = "cmdEventosVendidosHoy";
			this.cmdEventosVendidosHoy.UseUnderline = true;
			this.cmdEventosVendidosHoy.Label = "Vendidos hoy";
			this.hbox1.Add (this.cmdEventosVendidosHoy);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cmdEventosVendidosHoy]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.cmdEventosHoy = new global::Gtk.Button ();
			this.cmdEventosHoy.CanFocus = true;
			this.cmdEventosHoy.Name = "cmdEventosHoy";
			this.cmdEventosHoy.UseUnderline = true;
			this.cmdEventosHoy.Label = "Para hoy";
			this.hbox1.Add (this.cmdEventosHoy);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cmdEventosHoy]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.txtIDEvento = new global::Gtk.Entry ();
			this.txtIDEvento.CanFocus = true;
			this.txtIDEvento.Name = "txtIDEvento";
			this.txtIDEvento.IsEditable = true;
			this.txtIDEvento.InvisibleChar = '•';
			this.hbox1.Add (this.txtIDEvento);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.txtIDEvento]));
			w5.Position = 2;
			// Container child hbox1.Gtk.Box+BoxChild
			this.cmdBuscarEventos = new global::Gtk.Button ();
			this.cmdBuscarEventos.CanFocus = true;
			this.cmdBuscarEventos.Name = "cmdBuscarEventos";
			this.cmdBuscarEventos.UseUnderline = true;
			this.cmdBuscarEventos.Label = "Búscar";
			this.hbox1.Add (this.cmdBuscarEventos);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cmdBuscarEventos]));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			w1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox1]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeEventos = new global::Gtk.TreeView ();
			this.treeEventos.CanFocus = true;
			this.treeEventos.Name = "treeEventos";
			this.GtkScrolledWindow.Add (this.treeEventos);
			w1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(w1 [this.GtkScrolledWindow]));
			w9.Position = 2;
			// Internal child Taquilla.VisorEventos.ActionArea
			global::Gtk.HButtonBox w10 = this.ActionArea;
			w10.Name = "dialog1_ActionArea";
			w10.Spacing = 10;
			w10.BorderWidth = ((uint)(5));
			w10.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			// Container child buttonOk.Gtk.Container+ContainerChild
			global::Gtk.Alignment w11 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w12 = new global::Gtk.HBox ();
			w12.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w13 = new global::Gtk.Image ();
			w13.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Menu);
			w12.Add (w13);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w15 = new global::Gtk.Label ();
			w15.LabelProp = "_Cerrar";
			w15.UseUnderline = true;
			w12.Add (w15);
			w11.Add (w12);
			this.buttonOk.Add (w11);
			this.AddActionWidget (this.buttonOk, -7);
			global::Gtk.ButtonBox.ButtonBoxChild w19 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w10 [this.buttonOk]));
			w19.Expand = false;
			w19.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 924;
			this.DefaultHeight = 351;
			this.Show ();
			this.cmdEventosVendidosHoy.Clicked += new global::System.EventHandler (this.OnCmdEventosVendidosHoyClicked);
			this.cmdEventosHoy.Clicked += new global::System.EventHandler (this.OnCmdEventosHoyClicked);
			this.cmdBuscarEventos.Clicked += new global::System.EventHandler (this.OnCmdBuscarEventosClicked);
			this.treeEventos.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnTreeEventosKeyPressEvent);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
