
// This file has been generated by the GUI designer. Do not modify.
namespace Taquilla
{
	public partial class Registro
	{
		private global::Gtk.Alignment alignment1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeLog;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Taquilla.Registro
			this.Name = "Taquilla.Registro";
			this.Title = "Registro";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Taquilla.Registro.Gtk.Container+ContainerChild
			this.alignment1 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment1.Name = "alignment1";
			// Container child alignment1.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeLog = new global::Gtk.TreeView ();
			this.treeLog.CanFocus = true;
			this.treeLog.Name = "treeLog";
			this.GtkScrolledWindow.Add (this.treeLog);
			this.alignment1.Add (this.GtkScrolledWindow);
			this.Add (this.alignment1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1027;
			this.DefaultHeight = 504;
			this.Show ();
		}
	}
}
