
// This file has been generated by the GUI designer. Do not modify.
namespace Taquilla
{
	public partial class Ingresos
	{
		private global::Gtk.Table table1;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		private global::Gtk.Entry txtCantidad;

		private global::Gtk.Entry txtCodigoBarra;

		private global::Gtk.Label lblInformacion;

		private global::Gtk.HButtonBox dialog1_ActionArea;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		private global::Gtk.Button cmdLimpiar;

		private global::Gtk.Button button71;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Taquilla.Ingresos
			this.Name = "Taquilla.Ingresos";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Taquilla.Ingresos.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 1f;
			this.label1.LabelProp = "Código";
			this.table1.Add (this.label1);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 1f;
			this.label2.LabelProp = "Cantidad";
			this.table1.Add (this.label2);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.label2]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtCantidad = new global::Gtk.Entry ();
			this.txtCantidad.CanFocus = true;
			this.txtCantidad.Name = "txtCantidad";
			this.txtCantidad.IsEditable = true;
			this.txtCantidad.InvisibleChar = '•';
			this.table1.Add (this.txtCantidad);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.txtCantidad]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtCodigoBarra = new global::Gtk.Entry ();
			this.txtCodigoBarra.CanFocus = true;
			this.txtCodigoBarra.Name = "txtCodigoBarra";
			this.txtCodigoBarra.IsEditable = true;
			this.txtCodigoBarra.InvisibleChar = '•';
			this.table1.Add (this.txtCodigoBarra);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.txtCodigoBarra]));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add (this.table1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(w1[this.table1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.lblInformacion = new global::Gtk.Label ();
			this.lblInformacion.Name = "lblInformacion";
			this.lblInformacion.LabelProp = "Ingreso de productos";
			w1.Add (this.lblInformacion);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(w1[this.lblInformacion]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.dialog1_ActionArea = new global::Gtk.HButtonBox ();
			this.dialog1_ActionArea.Name = "dialog1_ActionArea";
			this.dialog1_ActionArea.Spacing = 10;
			this.dialog1_ActionArea.BorderWidth = ((uint)(5));
			this.dialog1_ActionArea.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.dialog1_ActionArea.Add (this.buttonCancel);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.dialog1_ActionArea[this.buttonCancel]));
			w8.Expand = false;
			w8.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			// Container child buttonOk.Gtk.Container+ContainerChild
			global::Gtk.Alignment w9 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w10 = new global::Gtk.HBox ();
			w10.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w11 = new global::Gtk.Image ();
			w11.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w10.Add (w11);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w13 = new global::Gtk.Label ();
			w13.LabelProp = "_Aceptar";
			w13.UseUnderline = true;
			w10.Add (w13);
			w9.Add (w10);
			this.buttonOk.Add (w9);
			this.dialog1_ActionArea.Add (this.buttonOk);
			global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.dialog1_ActionArea[this.buttonOk]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.cmdLimpiar = new global::Gtk.Button ();
			this.cmdLimpiar.CanFocus = true;
			this.cmdLimpiar.Name = "cmdLimpiar";
			this.cmdLimpiar.UseUnderline = true;
			// Container child cmdLimpiar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w18 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w19 = new global::Gtk.HBox ();
			w19.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w20 = new global::Gtk.Image ();
			w20.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-clear", global::Gtk.IconSize.Menu);
			w19.Add (w20);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w22 = new global::Gtk.Label ();
			w22.LabelProp = "Limpiar";
			w22.UseUnderline = true;
			w19.Add (w22);
			w18.Add (w19);
			this.cmdLimpiar.Add (w18);
			this.dialog1_ActionArea.Add (this.cmdLimpiar);
			global::Gtk.ButtonBox.ButtonBoxChild w26 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.dialog1_ActionArea[this.cmdLimpiar]));
			w26.Position = 2;
			w26.Expand = false;
			w26.Fill = false;
			w1.Add (this.dialog1_ActionArea);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(w1[this.dialog1_ActionArea]));
			w27.PackType = ((global::Gtk.PackType)(1));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			// Internal child Taquilla.Ingresos.ActionArea
			global::Gtk.HButtonBox w28 = this.ActionArea;
			w28.Name = "__gtksharp_69_Stetic_TopLevelDialog_ActionArea";
			// Container child __gtksharp_69_Stetic_TopLevelDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button71 = new global::Gtk.Button ();
			this.button71.CanFocus = true;
			this.button71.Name = "button71";
			this.button71.UseUnderline = true;
			this.button71.Label = "GtkButton";
			this.AddActionWidget (this.button71, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w29 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w28[this.button71]));
			w29.Expand = false;
			w29.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 176;
			this.Show ();
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
			this.cmdLimpiar.Clicked += new global::System.EventHandler (this.OnCmdLimpiarClicked);
		}
	}
}
