
// This file has been generated by the GUI designer. Do not modify.
namespace Taquilla
{
	public partial class Eventos
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label label10;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button cmdCancelar;
		private global::Gtk.Button cmdProgramar;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label label1;
		private global::Gtk.Label lblInfo;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Table table1;
		private global::Gtk.CheckButton chkCertificado;
		private global::Gtk.ComboBox cmbDuracion;
		private global::Gtk.ComboBox cmdHoraInicio;
		private global::Gtk.Label label11;
		private global::Gtk.Label label2;
		private global::Gtk.Label label7;
		private global::Gtk.Label lblAnfitrion;
		private global::Gtk.Label lblAnfitrion1;
		private global::Gtk.Label lblAnfitrion3;
		private global::Gtk.Entry txtinfoContacto;
		private global::Gtk.Entry txtNombreEvento;
		private global::Gtk.Entry txtPatrocinadoPor;
		private global::Gtk.Entry txtPrecioEvento;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label label4;
		private global::Gtk.Calendar calFechaEvento;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Taquilla.Eventos
			this.Name = "Taquilla.Eventos";
			this.Title = "Programador de eventos";
			this.TypeHint = ((global::Gdk.WindowTypeHint)(5));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Modal = true;
			this.BorderWidth = ((uint)(10));
			// Container child Taquilla.Eventos.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = "Nota: favor antes de programar el evento verificar disponibilidad, especialmente si es un cambio de hora.\nIngresar precio de evento/abono sin simbolo de dolar ($) y en el formato <b>0.00</b>";
			this.label10.UseMarkup = true;
			this.vbox2.Add (this.label10);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label10]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.cmdCancelar = new global::Gtk.Button ();
			this.cmdCancelar.CanFocus = true;
			this.cmdCancelar.Name = "cmdCancelar";
			this.cmdCancelar.UseUnderline = true;
			// Container child cmdCancelar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w2 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w3 = new global::Gtk.HBox ();
			w3.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w4 = new global::Gtk.Image ();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Menu);
			w3.Add (w4);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w6 = new global::Gtk.Label ();
			w6.LabelProp = "_Cancelar y salir";
			w6.UseUnderline = true;
			w3.Add (w6);
			w2.Add (w3);
			this.cmdCancelar.Add (w2);
			this.hbox1.Add (this.cmdCancelar);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cmdCancelar]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.cmdProgramar = new global::Gtk.Button ();
			this.cmdProgramar.Sensitive = false;
			this.cmdProgramar.CanFocus = true;
			this.cmdProgramar.Name = "cmdProgramar";
			this.cmdProgramar.UseUnderline = true;
			// Container child cmdProgramar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w11 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w12 = new global::Gtk.HBox ();
			w12.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w13 = new global::Gtk.Image ();
			w13.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-print", global::Gtk.IconSize.Menu);
			w12.Add (w13);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w15 = new global::Gtk.Label ();
			w15.LabelProp = "Guardar e _imprimir";
			w15.UseUnderline = true;
			w12.Add (w15);
			w11.Add (w12);
			this.cmdProgramar.Add (w11);
			this.hbox1.Add (this.cmdProgramar);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cmdProgramar]));
			w19.PackType = ((global::Gtk.PackType)(1));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w20.PackType = ((global::Gtk.PackType)(1));
			w20.Position = 1;
			w20.Expand = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = "<b>Previsualización</b>";
			this.label1.UseMarkup = true;
			this.vbox3.Add (this.label1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label1]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.lblInfo = new global::Gtk.Label ();
			this.lblInfo.Name = "lblInfo";
			this.vbox3.Add (this.lblInfo);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lblInfo]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.vbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox3]));
			w23.PackType = ((global::Gtk.PackType)(1));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(7)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.chkCertificado = new global::Gtk.CheckButton ();
			this.chkCertificado.CanFocus = true;
			this.chkCertificado.Name = "chkCertificado";
			this.chkCertificado.Label = "Es un certificado de regalo de evento";
			this.chkCertificado.DrawIndicator = true;
			this.chkCertificado.UseUnderline = true;
			this.table1.Add (this.chkCertificado);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table1 [this.chkCertificado]));
			w24.TopAttach = ((uint)(4));
			w24.BottomAttach = ((uint)(5));
			w24.LeftAttach = ((uint)(1));
			w24.RightAttach = ((uint)(2));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cmbDuracion = global::Gtk.ComboBox.NewText ();
			this.cmbDuracion.TooltipMarkup = "Duración del evento en formato HH:MM (Horas:Minutos)\nEj. Para un evento de 1 Hora escoger 01:00\nEj. Para un evento de 30 minutos escoger 00:30";
			this.cmbDuracion.Name = "cmbDuracion";
			this.table1.Add (this.cmbDuracion);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1 [this.cmbDuracion]));
			w25.TopAttach = ((uint)(6));
			w25.BottomAttach = ((uint)(7));
			w25.LeftAttach = ((uint)(1));
			w25.RightAttach = ((uint)(2));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cmdHoraInicio = global::Gtk.ComboBox.NewText ();
			this.cmdHoraInicio.TooltipMarkup = "Hora del primer juego del evento";
			this.cmdHoraInicio.Name = "cmdHoraInicio";
			this.table1.Add (this.cmdHoraInicio);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1 [this.cmdHoraInicio]));
			w26.TopAttach = ((uint)(5));
			w26.BottomAttach = ((uint)(6));
			w26.LeftAttach = ((uint)(1));
			w26.RightAttach = ((uint)(2));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 1F;
			this.label11.LabelProp = "Hora de inicio";
			this.table1.Add (this.label11);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1 [this.label11]));
			w27.TopAttach = ((uint)(5));
			w27.BottomAttach = ((uint)(6));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = "Nombre del evento";
			this.table1.Add (this.label2);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
			w28.TopAttach = ((uint)(3));
			w28.BottomAttach = ((uint)(4));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 1F;
			this.label7.LabelProp = "Duración";
			this.table1.Add (this.label7);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table1 [this.label7]));
			w29.TopAttach = ((uint)(6));
			w29.BottomAttach = ((uint)(7));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblAnfitrion = new global::Gtk.Label ();
			this.lblAnfitrion.Name = "lblAnfitrion";
			this.lblAnfitrion.Xalign = 1F;
			this.lblAnfitrion.LabelProp = "Patrocinado por";
			this.table1.Add (this.lblAnfitrion);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblAnfitrion]));
			w30.TopAttach = ((uint)(1));
			w30.BottomAttach = ((uint)(2));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblAnfitrion1 = new global::Gtk.Label ();
			this.lblAnfitrion1.Name = "lblAnfitrion1";
			this.lblAnfitrion1.Xalign = 1F;
			this.lblAnfitrion1.LabelProp = "Precio evento ($)";
			this.table1.Add (this.lblAnfitrion1);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblAnfitrion1]));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblAnfitrion3 = new global::Gtk.Label ();
			this.lblAnfitrion3.Name = "lblAnfitrion3";
			this.lblAnfitrion3.Xalign = 1F;
			this.lblAnfitrion3.LabelProp = "Inf. contacto";
			this.table1.Add (this.lblAnfitrion3);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblAnfitrion3]));
			w32.TopAttach = ((uint)(2));
			w32.BottomAttach = ((uint)(3));
			w32.XOptions = ((global::Gtk.AttachOptions)(4));
			w32.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtinfoContacto = new global::Gtk.Entry ();
			this.txtinfoContacto.TooltipMarkup = "Télefono, correo electrónico, viper, etc.";
			this.txtinfoContacto.CanFocus = true;
			this.txtinfoContacto.Name = "txtinfoContacto";
			this.txtinfoContacto.IsEditable = true;
			this.txtinfoContacto.InvisibleChar = '•';
			this.table1.Add (this.txtinfoContacto);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtinfoContacto]));
			w33.TopAttach = ((uint)(2));
			w33.BottomAttach = ((uint)(3));
			w33.LeftAttach = ((uint)(1));
			w33.RightAttach = ((uint)(2));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtNombreEvento = new global::Gtk.Entry ();
			this.txtNombreEvento.TooltipMarkup = "Nombre del cumpleañero, promoción, etc.";
			this.txtNombreEvento.CanFocus = true;
			this.txtNombreEvento.Name = "txtNombreEvento";
			this.txtNombreEvento.IsEditable = true;
			this.txtNombreEvento.InvisibleChar = '•';
			this.table1.Add (this.txtNombreEvento);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtNombreEvento]));
			w34.TopAttach = ((uint)(3));
			w34.BottomAttach = ((uint)(4));
			w34.LeftAttach = ((uint)(1));
			w34.RightAttach = ((uint)(2));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtPatrocinadoPor = new global::Gtk.Entry ();
			this.txtPatrocinadoPor.CanFocus = true;
			this.txtPatrocinadoPor.Name = "txtPatrocinadoPor";
			this.txtPatrocinadoPor.IsEditable = true;
			this.txtPatrocinadoPor.InvisibleChar = '•';
			this.table1.Add (this.txtPatrocinadoPor);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtPatrocinadoPor]));
			w35.TopAttach = ((uint)(1));
			w35.BottomAttach = ((uint)(2));
			w35.LeftAttach = ((uint)(1));
			w35.RightAttach = ((uint)(2));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.txtPrecioEvento = new global::Gtk.Entry ();
			this.txtPrecioEvento.TooltipMarkup = "Precio ($) total del evento a cobrar por RIFT.";
			this.txtPrecioEvento.CanFocus = true;
			this.txtPrecioEvento.Name = "txtPrecioEvento";
			this.txtPrecioEvento.IsEditable = true;
			this.txtPrecioEvento.InvisibleChar = '•';
			this.table1.Add (this.txtPrecioEvento);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table1 [this.txtPrecioEvento]));
			w36.LeftAttach = ((uint)(1));
			w36.RightAttach = ((uint)(2));
			w36.XOptions = ((global::Gtk.AttachOptions)(4));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox2.Add (this.table1);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.table1]));
			w37.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = "Fecha de evento";
			this.vbox4.Add (this.label4);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label4]));
			w38.Position = 0;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.calFechaEvento = new global::Gtk.Calendar ();
			this.calFechaEvento.CanFocus = true;
			this.calFechaEvento.Name = "calFechaEvento";
			this.calFechaEvento.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.vbox4.Add (this.calFechaEvento);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.calFechaEvento]));
			w39.Position = 1;
			w39.Expand = false;
			w39.Fill = false;
			this.hbox2.Add (this.vbox4);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox4]));
			w40.Position = 1;
			w40.Expand = false;
			w40.Fill = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w41.PackType = ((global::Gtk.PackType)(1));
			w41.Position = 3;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 740;
			this.DefaultHeight = 437;
			this.Show ();
			this.chkCertificado.Toggled += new global::System.EventHandler (this.OnChkCertificadoToggled);
			this.cmdCancelar.Clicked += new global::System.EventHandler (this.OnCmdCancelarClicked);
			this.cmdProgramar.Clicked += new global::System.EventHandler (this.OnCmdProgramarClicked);
		}
	}
}
